export const initialPrinters = [
  {
    id: 'printer-1',
    name: 'Creality K1 Max',
    model: 'CoreXY High-Speed (Klipper)',
    status: 'printing',
    nozzleTemp: 230,
    targetNozzleTemp: 230,
    bedTemp: 65,
    targetBedTemp: 65,
    speedFactor: 100,
    currentJobId: 'job-4',
    progress: 68,
    elapsedSeconds: 2850,
    totalSeconds: 4200,
    maxBuildVolume: '300 x 300 x 300 mm'
  },
  {
    id: 'printer-2',
    name: 'Bambu Lab H2D',
    model: 'CoreXY Multi-Material',
    status: 'idle',
    nozzleTemp: 26,
    targetNozzleTemp: 0,
    bedTemp: 25,
    targetBedTemp: 0,
    speedFactor: 100,
    currentJobId: null,
    progress: 0,
    elapsedSeconds: 0,
    totalSeconds: 0,
    maxBuildVolume: '256 x 256 x 256 mm'
  },
  {
    id: 'printer-3',
    name: 'Ultimaker 2',
    model: 'Bowden Precision FDM',
    status: 'idle',
    nozzleTemp: 28,
    targetNozzleTemp: 0,
    bedTemp: 24,
    targetBedTemp: 0,
    speedFactor: 100,
    currentJobId: null,
    progress: 0,
    elapsedSeconds: 0,
    totalSeconds: 0,
    maxBuildVolume: '223 x 223 x 205 mm'
  }
];

export const initialSpools = [
  {
    id: 'spool-1',
    name: 'Creality Hyper PLA',
    material: 'PLA',
    colorName: 'Preto Jet',
    colorHex: '#1e293b',
    totalWeight: 1000,
    remainingWeight: 780,
    diameter: 1.75,
    pricePerKg: 110.0,
    brand: 'Creality'
  },
  {
    id: 'spool-2',
    name: 'eSun PETG Tough',
    material: 'PETG',
    colorName: 'Azul Cyan Transparent',
    colorHex: '#06b6d4',
    totalWeight: 1000,
    remainingWeight: 420,
    diameter: 1.75,
    pricePerKg: 130.0,
    brand: 'eSun'
  },
  {
    id: 'spool-3',
    name: 'Bambu Tough PLA',
    material: 'PLA',
    colorName: 'Laranja Solar',
    colorHex: '#f97316',
    totalWeight: 1000,
    remainingWeight: 950,
    diameter: 1.75,
    pricePerKg: 160.0,
    brand: 'Bambu Lab'
  },
  {
    id: 'spool-4',
    name: 'Sunlu TPU 95A',
    material: 'TPU',
    colorName: 'Vermelho Ruby Flex',
    colorHex: '#ef4444',
    totalWeight: 500,
    remainingWeight: 310,
    diameter: 1.75,
    pricePerKg: 280.0,
    brand: 'Sunlu'
  },
  {
    id: 'spool-5',
    name: 'Voxelab ABS High Temp',
    material: 'ABS',
    colorName: 'Cinza Industrial',
    colorHex: '#64748b',
    totalWeight: 1000,
    remainingWeight: 90,
    diameter: 1.75,
    pricePerKg: 95.0,
    brand: 'Voxelab'
  }
];

export const initialProjects = [
  {
    id: 'proj-1',
    title: 'Robô Hexápode Articulado v2',
    responsible: 'Eng. Ricardo Oliveira',
    customer: 'Departamento de Mecatrônica',
    deadline: '2026-09-05',
    materialRequirement: 'PETG',
    colorRequirement: 'Azul Cyan Transparent / Preto',
    status: 'in_progress',
    notes: 'Peças de alta resistência estrutural para os motores servo de alto torque.',
    parts: [
      {
        id: 'part-1-1',
        name: 'Braço Articulado Principal',
        quantityRequired: 6,
        quantityPrinted: 2,
        estimatedTimeHours: 1,
        estimatedTimeMinutes: 45,
        estimatedWeightGrams: 85,
        materialType: 'PETG',
        fileName: 'Braco_Hexapode_v2.stl'
      },
      {
        id: 'part-1-2',
        name: 'Base Central do Chassi',
        quantityRequired: 1,
        quantityPrinted: 1,
        estimatedTimeHours: 4,
        estimatedTimeMinutes: 15,
        estimatedWeightGrams: 320,
        materialType: 'PLA',
        fileName: 'Base_Chassi_Hexapode.gcode'
      },
      {
        id: 'part-1-3',
        name: 'Suporte dos Servomotores',
        quantityRequired: 6,
        quantityPrinted: 0,
        estimatedTimeHours: 0,
        estimatedTimeMinutes: 50,
        estimatedWeightGrams: 45,
        materialType: 'PETG',
        fileName: 'Suporte_Servo_Hex.3mf'
      }
    ]
  },
  {
    id: 'proj-2',
    title: 'Kit Suportes de Painel Solar FPV',
    responsible: 'Mariana Santos',
    customer: 'Energia Renovável Lab',
    deadline: '2026-08-30',
    materialRequirement: 'ABS',
    colorRequirement: 'Cinza Industrial',
    status: 'in_progress',
    notes: 'Resistente a raios UV e alta temperatura ambiente (exposição solar).',
    parts: [
      {
        id: 'part-2-1',
        name: 'Fixador Angular 45 Graus',
        quantityRequired: 4,
        quantityPrinted: 2,
        estimatedTimeHours: 1,
        estimatedTimeMinutes: 10,
        estimatedWeightGrams: 60,
        materialType: 'ABS',
        fileName: 'Fixador_Angular_45.gcode'
      },
      {
        id: 'part-2-2',
        name: 'Grampo de Pressão Lateral',
        quantityRequired: 8,
        quantityPrinted: 0,
        estimatedTimeHours: 0,
        estimatedTimeMinutes: 30,
        estimatedWeightGrams: 25,
        materialType: 'ABS',
        fileName: 'Grampo_Pressao_Solar.stl'
      }
    ]
  }
];

export const initialJobs = [
  {
    id: 'job-1',
    title: 'Suporte Articulado VESA 100mm',
    customer: 'Tech Lab Solutions',
    projectId: 'proj-1',
    partName: 'Base Central do Chassi',
    copyNumber: 1,
    totalCopies: 1,
    fileName: 'Suporte_VESA_Heavy_v2.gcode',
    fileSize: 15518976,
    fileType: 'gcode',
    materialType: 'PLA',
    spoolId: 'spool-1',
    estimatedTimeHours: 4,
    estimatedTimeMinutes: 15,
    estimatedWeightGrams: 320,
    layerHeight: 0.2,
    infillPercentage: 35,
    priority: 'high',
    status: 'queued',
    assignedPrinterId: null,
    createdAt: '2026-08-19T14:30:00.000Z',
    completedAt: null,
    notes: 'Imprimir com 4 perímetros de parede para alta resistência estrutural.',
    sampleGcode: `; GCODE Preservado - Suporte VESA 100mm\nM104 S220\nM140 S60\nG28\nG1 Z0.2 F3000`
  },
  {
    id: 'job-2',
    title: 'Engrenagem Helicoidal Dupla (Cópia 1/6)',
    customer: 'Engenharia Mecânica Robô',
    projectId: 'proj-1',
    partName: 'Braço Articulado Principal',
    copyNumber: 1,
    totalCopies: 6,
    fileName: 'Dual_Helical_Gear_Drive.stl',
    fileSize: 8598323,
    fileType: 'stl',
    materialType: 'PETG',
    spoolId: 'spool-2',
    estimatedTimeHours: 1,
    estimatedTimeMinutes: 45,
    estimatedWeightGrams: 85,
    layerHeight: 0.16,
    infillPercentage: 100,
    priority: 'urgent',
    status: 'queued',
    assignedPrinterId: null,
    createdAt: '2026-08-19T16:15:00.000Z',
    completedAt: null,
    notes: 'Preenchimento 100% para resistência ao cisalhamento do motor.',
    sampleGcode: `; STL File: Dual_Helical_Gear_Drive.stl`
  },
  {
    id: 'job-3',
    title: 'Organizador de Cabos de Mesa Slim',
    customer: 'Ana Paula - Studio Design',
    projectId: null,
    partName: null,
    copyNumber: 1,
    totalCopies: 1,
    fileName: 'Cable_Organizer_Slim.3mf',
    fileSize: 3565158,
    fileType: '3mf',
    materialType: 'PLA',
    spoolId: 'spool-3',
    estimatedTimeHours: 0,
    estimatedTimeMinutes: 50,
    estimatedWeightGrams: 45,
    layerHeight: 0.2,
    infillPercentage: 15,
    priority: 'normal',
    status: 'queued',
    assignedPrinterId: null,
    createdAt: '2026-08-19T18:00:00.000Z',
    completedAt: null,
    notes: 'Usar cor Laranja Solar.',
    sampleGcode: `; 3MF Container Package Stream Data`
  },
  {
    id: 'job-4',
    title: 'Fixador Angular 45 Graus (Cópia 1/4)',
    customer: 'Energia Renovável Lab',
    projectId: 'proj-2',
    partName: 'Fixador Angular 45 Graus',
    copyNumber: 1,
    totalCopies: 4,
    fileName: 'Fixador_Angular_45.gcode',
    fileSize: 5347737,
    fileType: 'gcode',
    materialType: 'ABS',
    spoolId: 'spool-5',
    estimatedTimeHours: 1,
    estimatedTimeMinutes: 10,
    estimatedWeightGrams: 60,
    layerHeight: 0.2,
    infillPercentage: 30,
    priority: 'high',
    status: 'printing',
    assignedPrinterId: 'printer-1',
    createdAt: '2026-08-19T19:00:00.000Z',
    completedAt: null,
    notes: 'Projeto Painel Solar. Imprimindo na Creality K1 Max.',
    sampleGcode: `; GCODE - Fixador Angular`
  },
  {
    id: 'job-5',
    title: 'Chaveiro Dragão Articulado',
    customer: 'Gamer Shop',
    projectId: null,
    partName: null,
    copyNumber: 1,
    totalCopies: 1,
    fileName: 'Dragon_Keychain_Flex.stl',
    fileSize: 19818086,
    fileType: 'stl',
    materialType: 'TPU',
    spoolId: 'spool-4',
    estimatedTimeHours: 2,
    estimatedTimeMinutes: 30,
    estimatedWeightGrams: 120,
    layerHeight: 0.2,
    infillPercentage: 20,
    priority: 'low',
    status: 'completed',
    assignedPrinterId: 'printer-3',
    createdAt: '2026-08-19T10:00:00.000Z',
    completedAt: '2026-08-19T12:30:00.000Z',
    notes: 'Impressão concluída na Ultimaker 2 com sucesso.',
    sampleGcode: `; Dragon Keychain Flex STL`
  }
];
